"""Install a Pi05 runner that shifts the Droid/Franka robot base pose slightly."""
from __future__ import annotations

import argparse
from pathlib import Path

RUNNER_CODE = r"""# Auto-generated by create_robot_base_shift_runner.py.
import argparse
import copy
import sys
import traceback

import cv2  # noqa: F401 -- must import before isaaclab.
from isaaclab.app import AppLauncher

PI0_VARIANTS = ["pi0", "pi0_fast", "pi05", "paligemma", "paligemma_fast"]

parser = argparse.ArgumentParser(description="Evaluate Pi0-family policy with a shifted robot base pose.")
parser.add_argument("--policy", choices=PI0_VARIANTS, default="pi05")
parser.add_argument("--remote-host", "--remote_host", type=str, default="localhost")
parser.add_argument("--remote-port", "--remote_port", type=int, default=8000)
parser.add_argument("--remote-uri", "--remote_uri", type=str, default=None)
parser.add_argument("--open-loop-horizon", "--open_loop_horizon", type=int, default=None)
parser.add_argument("--robot-x-offset", type=float, default=0.03)
parser.add_argument("--robot-y-offset", type=float, default=0.0)
parser.add_argument("--enable-verbose", "--enable_verbose", action="store_true")
parser.add_argument("--enable-debug", "--enable_debug", action="store_true")
parser.add_argument("--record-image-data", "--record_image_data", action="store_true")

from robolab.eval.runner import add_common_eval_args, run_evaluation  # noqa: E402

add_common_eval_args(parser)
AppLauncher.add_app_launcher_args(parser)
args_cli, _ = parser.parse_known_args()
args_cli.enable_cameras = True

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

from isaaclab.utils import configclass  # noqa: E402
import robolab.constants  # noqa: E402
from robolab.constants import TASK_DIR  # noqa: E402
from robolab.core.environments.factory import auto_discover_and_create_cfgs  # noqa: E402
from robolab.core.observations.observation_utils import generate_image_obs_from_cameras, generate_obs_cfg  # noqa: E402
from robolab.registrations.droid.camera_presets import WRIST_LEFT  # noqa: E402
from robolab.robots.droid import DroidCfg, DroidJointPositionActionCfg, ProprioceptionObservationCfg, WristCameraCfg, contact_gripper  # noqa: E402
from robolab.variations.backgrounds import HomeOfficeBackgroundCfg  # noqa: E402
from robolab.variations.camera import EgocentricMirroredCameraCfg  # noqa: E402
from robolab.variations.lighting import SphereLightCfg  # noqa: E402
from policies.pi0_family.client import Pi0DroidJointposClient  # noqa: E402

robolab.constants.ENABLE_SUBTASK_PROGRESS_CHECKING = args_cli.enable_subtask
robolab.constants.RECORD_IMAGE_DATA = args_cli.record_image_data
robolab.constants.VERBOSE = args_cli.enable_verbose
robolab.constants.DEBUG = args_cli.enable_debug


def make_shifted_robot_cfg(x_offset: float, y_offset: float):
    base = DroidCfg()

    @configclass
    class DroidBaseShiftCfg:
        robot = copy.deepcopy(base.robot)
        robot.init_state.pos = (float(x_offset), float(y_offset), 0.0)
        wrist_cam = copy.deepcopy(base.wrist_cam)
        frames = copy.deepcopy(base.frames)
    return DroidBaseShiftCfg


def register_shifted_envs() -> None:
    image_obs_cfg = generate_image_obs_from_cameras(WRIST_LEFT)
    viewport_cfg = generate_image_obs_from_cameras([EgocentricMirroredCameraCfg])
    observation_cfg = generate_obs_cfg({
        "image_obs": image_obs_cfg(),
        "proprio_obs": ProprioceptionObservationCfg(),
        "viewport_cam": viewport_cfg(),
    })
    scene_cameras = [camera for camera in WRIST_LEFT if camera is not WristCameraCfg]
    auto_discover_and_create_cfgs(
        task_dir=TASK_DIR,
        task_subdirs=args_cli.task_dirs,
        tasks=args_cli.task,
        pattern="*.py",
        env_prefix="",
        env_postfix="RobotBaseShift",
        observations_cfg=observation_cfg(),
        actions_cfg=DroidJointPositionActionCfg(),
        robot_cfg=make_shifted_robot_cfg(args_cli.robot_x_offset, args_cli.robot_y_offset),
        camera_cfg=[*scene_cameras, EgocentricMirroredCameraCfg],
        lighting_cfg=SphereLightCfg,
        background_cfg=HomeOfficeBackgroundCfg,
        contact_gripper=contact_gripper,
        dt=1 / (60 * 2),
        render_interval=8,
        decimation=8,
        seed=1,
    )


def make_client(args: argparse.Namespace) -> Pi0DroidJointposClient:
    kwargs = dict(
        remote_host=args.remote_host,
        remote_port=args.remote_port,
        remote_uri=args.remote_uri,
        open_loop_horizon=args.open_loop_horizon,
        policy_variant=args.policy,
    )
    return Pi0DroidJointposClient(**{k: v for k, v in kwargs.items() if v is not None})


def main() -> None:
    register_shifted_envs()
    run_evaluation(args_cli, policy=f"{args_cli.policy}_robot_base_shift", client_factory=make_client)
    simulation_app.close()


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"[RoboLab] Terminated with error: {e}")
        traceback.print_exc()
        simulation_app.close()
        sys.exit(1)
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--robolab-root", type=Path, required=True)
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()
    out = args.robolab_root / "policies" / "pi0_family" / "run_robot_base_shift.py"
    if out.exists() and not args.force:
        raise FileExistsError(f"{out} exists; pass --force")
    out.write_text(RUNNER_CODE, encoding="utf-8")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
