"""Install a RoboLab object-position perturbation runner.

This complements official lighting/background/camera variation scripts. It adds a
Pi0-family runner that randomizes named rigid objects at reset using Isaac Lab's
root-pose reset pattern.
"""

from __future__ import annotations

import argparse
from pathlib import Path


EVENTS_CODE = r'''# Auto-generated by create_object_position_variation_runner.py.
import torch
import isaaclab.utils.math as math_utils
from isaaclab.envs import ManagerBasedEnv


def reset_named_object_pose_uniform(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    object_names: list[str],
    pose_range: dict[str, tuple[float, float]],
    velocity_range: dict[str, tuple[float, float]] | None = None,
):
    """Randomize named rigid object root poses around their default poses."""
    velocity_range = velocity_range or {}
    for object_name in object_names:
        if object_name not in env.scene.rigid_objects:
            print(f"[object-position-variation] skip missing rigid object: {object_name}")
            continue
        asset = env.scene.rigid_objects[object_name]
        root_states = asset.data.default_root_state[env_ids].clone()

        pose_ranges = torch.tensor(
            [pose_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]],
            device=asset.device,
        )
        samples = math_utils.sample_uniform(pose_ranges[:, 0], pose_ranges[:, 1], (len(env_ids), 6), device=asset.device)
        positions = root_states[:, 0:3] + env.scene.env_origins[env_ids] + samples[:, 0:3]
        orientation_delta = math_utils.quat_from_euler_xyz(samples[:, 3], samples[:, 4], samples[:, 5])
        orientations = math_utils.quat_mul(root_states[:, 3:7], orientation_delta)

        velocity_ranges = torch.tensor(
            [velocity_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]],
            device=asset.device,
        )
        velocity_samples = math_utils.sample_uniform(
            velocity_ranges[:, 0], velocity_ranges[:, 1], (len(env_ids), 6), device=asset.device
        )
        velocities = root_states[:, 7:13] + velocity_samples

        asset.write_root_pose_to_sim(torch.cat([positions, orientations], dim=-1), env_ids=env_ids)
        asset.write_root_velocity_to_sim(velocities, env_ids=env_ids)
'''


RUNNER_CODE = r'''# Auto-generated by create_object_position_variation_runner.py.
import argparse
import os
import sys
import traceback

import cv2  # noqa: F401 -- must import this before isaaclab.
from isaaclab.app import AppLauncher
from isaaclab.managers import EventTermCfg as EventTerm
from robolab.constants import DEFAULT_TASK_SUBFOLDERS, PACKAGE_DIR, get_timestamp, set_output_dir

parser = argparse.ArgumentParser(description="Run Pi0-family evaluation with named object position perturbations.")
parser.add_argument("--num-envs", "--num_envs", type=int, default=1)
AppLauncher.add_app_launcher_args(parser)
parser.add_argument("--task", nargs="+", required=True)
parser.add_argument("--tag", nargs="+", default=None)
parser.add_argument("--task-dirs", nargs="+", default=DEFAULT_TASK_SUBFOLDERS)
parser.add_argument("--policy", choices=["pi0", "pi0_fast", "paligemma", "paligemma_fast", "pi05"], default="pi05")
parser.add_argument("--num-runs", "--num_runs", type=int, default=1)
parser.add_argument("--enable-subtask", "--enable_subtask", action="store_true")
parser.add_argument("--record-image-data", "--record_image_data", action="store_true")
parser.add_argument("--output-folder-name", "--output_folder_name", type=str, default=None)
parser.add_argument("--enable-verbose", "--enable_verbose", action="store_true")
parser.add_argument("--enable-debug", "--enable_debug", action="store_true")
parser.add_argument("--remote-host", "--remote_host", type=str, default="localhost")
parser.add_argument("--remote-port", "--remote_port", type=int, default=8000)
parser.add_argument("--video-mode", "--video_mode", type=str, default="all")
parser.add_argument("--object-name", "--object_name", nargs="+", required=True)
parser.add_argument("--xy-range", "--xy_range", type=float, default=0.03)
parser.add_argument("--yaw-range", "--yaw_range", type=float, default=0.20)
args_cli, _ = parser.parse_known_args()
args_cli.enable_cameras = True
args_cli.save_videos = True

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

import robolab.constants  # noqa: E402
from robolab.core.environments.factory import get_envs  # noqa: E402
from robolab.core.environments.runtime import create_env  # noqa: E402
from robolab.core.logging.results import check_all_episodes_complete, check_run_complete  # noqa: E402
from robolab.core.logging.results import init_experiment, summarize_experiment_results  # noqa: E402
from robolab.eval import run_episode, summarize_run  # noqa: E402
from robolab.registrations.droid.auto_env_registrations_jointpos import auto_register_droid_envs  # noqa: E402
from policies.pi0_family.client import Pi0DroidJointposClient  # noqa: E402
from policies.pi0_family.object_position_events import reset_named_object_pose_uniform  # noqa: E402

robolab.constants.ENABLE_SUBTASK_PROGRESS_CHECKING = args_cli.enable_subtask
robolab.constants.RECORD_IMAGE_DATA = args_cli.record_image_data
robolab.constants.VERBOSE = args_cli.enable_verbose
robolab.constants.DEBUG = args_cli.enable_debug

auto_register_droid_envs(task_dirs=args_cli.task_dirs)

pose_range = {
    "x": (-args_cli.xy_range, args_cli.xy_range),
    "y": (-args_cli.xy_range, args_cli.xy_range),
    "z": (0.0, 0.0),
    "roll": (0.0, 0.0),
    "pitch": (0.0, 0.0),
    "yaw": (-args_cli.yaw_range, args_cli.yaw_range),
}

object_pose_event = {
    "randomize_object_position": EventTerm(
        func=reset_named_object_pose_uniform,
        mode="reset",
        params={
            "object_names": args_cli.object_name,
            "pose_range": pose_range,
            "velocity_range": {},
        },
    )
}


def main() -> None:
    if args_cli.output_folder_name is None:
        args_cli.output_folder_name = get_timestamp() + f"_{args_cli.policy}_object_position_variation"
    output_dir = os.path.join(PACKAGE_DIR, "output", args_cli.output_folder_name)
    os.makedirs(output_dir, exist_ok=True)

    task_envs = get_envs(task=args_cli.task) if args_cli.task else get_envs(tag=args_cli.tag) if args_cli.tag else get_envs()
    num_envs = args_cli.num_envs
    num_runs = args_cli.num_runs
    total_episodes = num_runs * num_envs
    print(f"Output directory: {output_dir}")
    print(f"Running {len(task_envs)} task(s), object_names={args_cli.object_name}, pose_range={pose_range}")

    episode_results_file, episode_results = init_experiment(output_dir)
    for base_task_env in task_envs:
        task_env = f"{base_task_env}_ObjectPosition"
        scene_output_dir = os.path.join(output_dir, task_env)
        os.makedirs(scene_output_dir, exist_ok=True)
        set_output_dir(scene_output_dir)

        if check_all_episodes_complete(episode_results=episode_results, env_name=task_env, num_episodes=total_episodes):
            print(f"\033[96m[RoboLab] Task `{task_env}` already done. Skipping.\033[0m")
            continue

        env, env_cfg = create_env(
            base_task_env,
            device=args_cli.device,
            num_envs=num_envs,
            use_fabric=True,
            events=object_pose_event,
            policy=args_cli.policy,
        )
        client = Pi0DroidJointposClient(
            policy_variant=args_cli.policy,
            remote_host=args_cli.remote_host,
            remote_port=args_cli.remote_port,
        )
        for run_idx in range(num_runs):
            run_episode_ids = [run_idx * num_envs + eid for eid in range(num_envs)]
            if all(check_run_complete(episode_results=episode_results, env_name=task_env, episode=ep_id) for ep_id in run_episode_ids):
                print(f"\033[96m[RoboLab] Task `{task_env}` run `{run_idx}` already done. Skipping.\033[0m")
                continue
            run_name = task_env + f"_{run_idx}"
            env_results, msgs, timing = run_episode(
                env=env,
                env_cfg=env_cfg,
                episode=run_idx,
                client=client,
                save_videos=args_cli.save_videos,
                headless=args_cli.headless,
            )
            episode_results = summarize_run(
                env_results=env_results,
                msgs=msgs,
                env=env,
                env_cfg=env_cfg,
                num_envs=num_envs,
                run_idx=run_idx,
                run_name=run_name,
                task_env=task_env,
                scene_output_dir=scene_output_dir,
                policy=args_cli.policy,
                episode_results=episode_results,
                episode_results_file=episode_results_file,
                enable_subtask_progress=robolab.constants.ENABLE_SUBTASK_PROGRESS_CHECKING,
                task_name=base_task_env,
                extra_fields={
                    "object_position_variation": True,
                    "object_names": ",".join(args_cli.object_name),
                    "object_xy_range": args_cli.xy_range,
                    "object_yaw_range": args_cli.yaw_range,
                },
            )
            env.reset_eval_state()
        env.close()
    summarize_experiment_results(episode_results)
    simulation_app.close()


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"\033[96m[RoboLab] Terminated with error: {e}\033[0m")
        traceback.print_exc()
        simulation_app.close()
        sys.exit(1)
'''


def write(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists; pass --force to overwrite")
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--robolab-root", type=Path, default=Path.cwd())
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    root = args.robolab_root.resolve()
    policy_dir = root / "policies" / "pi0_family"
    if not (policy_dir / "client.py").exists():
        raise FileNotFoundError(f"RoboLab Pi0-family client not found under {policy_dir}")
    write(policy_dir / "object_position_events.py", EVENTS_CODE, args.force)
    write(policy_dir / "run_object_position_variation.py", RUNNER_CODE, args.force)


if __name__ == "__main__":
    main()
