"""Install a RoboLab Pi05 wrist-camera soft-ablation runner.

Run this on the 4090 RoboLab checkout:

    python create_pi05_wrist_blackout_runner.py --robolab-root /path/to/RoboLab --force

It creates two files inside the RoboLab repo:

    policies/pi0_family/client_wrist_blackout.py
    policies/pi0_family/run_wrist_blackout.py

The client keeps the normal Pi05 observation schema but zeros only the wrist image
before packing the OpenPI request. This is a soft ablation: Isaac still renders
the wrist camera, but the policy cannot use wrist visual content.
"""

from __future__ import annotations

import argparse
from pathlib import Path


CLIENT_CODE = r'''# Auto-generated by create_pi05_wrist_blackout_runner.py.
import numpy as np

from policies.pi0_family.client import Pi0DroidJointposClient


class Pi0DroidJointposWristBlackoutClient(Pi0DroidJointposClient):
    """Pi0/Pi05 client variant that blacks out wrist images before inference."""

    def _pack_request(self, extracted_obs: dict, instruction: str) -> dict:
        extracted_obs = dict(extracted_obs)
        extracted_obs["wrist_image"] = np.zeros_like(extracted_obs["wrist_image"])
        return super()._pack_request(extracted_obs, instruction)
'''


RUNNER_CODE = r'''# Auto-generated by create_pi05_wrist_blackout_runner.py.
import argparse
import sys
import traceback

import cv2  # noqa: F401 -- must import this before isaaclab.
from isaaclab.app import AppLauncher

PI0_VARIANTS = ["pi0", "pi0_fast", "pi05", "paligemma", "paligemma_fast"]

parser = argparse.ArgumentParser(description="Evaluate Pi0-family policy with wrist camera blacked out.")
parser.add_argument("--policy", choices=PI0_VARIANTS, default="pi05")
parser.add_argument("--remote-host", "--remote_host", type=str, default="localhost")
parser.add_argument("--remote-port", "--remote_port", type=int, default=8000)
parser.add_argument("--remote-uri", "--remote_uri", type=str, default=None)
parser.add_argument("--open-loop-horizon", "--open_loop_horizon", type=int, default=None)
parser.add_argument("--enable-verbose", "--enable_verbose", action="store_true")
parser.add_argument("--enable-debug", "--enable_debug", action="store_true")
parser.add_argument("--record-image-data", "--record_image_data", action="store_true")
parser.add_argument("--randomize-background", "--randomize_background", action="store_true")
parser.add_argument("--background-seed", "--background_seed", type=int, default=None)

from robolab.eval.runner import add_common_eval_args, run_evaluation  # noqa: E402

add_common_eval_args(parser)
AppLauncher.add_app_launcher_args(parser)
args_cli, _ = parser.parse_known_args()
args_cli.enable_cameras = True

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

import robolab.constants  # noqa: E402
from robolab.registrations.droid.auto_env_registrations_jointpos import auto_register_droid_envs  # noqa: E402
from policies.pi0_family.client_wrist_blackout import Pi0DroidJointposWristBlackoutClient  # noqa: E402

robolab.constants.ENABLE_SUBTASK_PROGRESS_CHECKING = args_cli.enable_subtask
robolab.constants.RECORD_IMAGE_DATA = args_cli.record_image_data
robolab.constants.VERBOSE = args_cli.enable_verbose
robolab.constants.DEBUG = args_cli.enable_debug

auto_register_droid_envs(
    task_dirs=args_cli.task_dirs,
    task=args_cli.task,
    randomize_background=args_cli.randomize_background,
    background_seed=args_cli.background_seed,
)


def make_client(args: argparse.Namespace) -> Pi0DroidJointposWristBlackoutClient:
    kwargs = dict(
        remote_host=args.remote_host,
        remote_port=args.remote_port,
        remote_uri=args.remote_uri,
        open_loop_horizon=args.open_loop_horizon,
        policy_variant=args.policy,
    )
    return Pi0DroidJointposWristBlackoutClient(**{k: v for k, v in kwargs.items() if v is not None})


def main() -> None:
    run_evaluation(args_cli, policy=f"{args_cli.policy}_wrist_blackout", client_factory=make_client)
    simulation_app.close()


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"\033[96m[RoboLab] Terminated with error: {e}\033[0m")
        traceback.print_exc()
        simulation_app.close()
        sys.exit(1)
'''


def write_file(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists; pass --force to overwrite")
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--robolab-root", type=Path, default=Path.cwd())
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    root = args.robolab_root.resolve()
    policy_dir = root / "policies" / "pi0_family"
    if not (policy_dir / "client.py").exists():
        raise FileNotFoundError(f"RoboLab Pi0-family client not found under {policy_dir}")
    if not (root / "robolab").exists():
        raise FileNotFoundError(f"RoboLab package directory not found under {root}")

    write_file(policy_dir / "client_wrist_blackout.py", CLIENT_CODE, args.force)
    write_file(policy_dir / "run_wrist_blackout.py", RUNNER_CODE, args.force)


if __name__ == "__main__":
    main()
